### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by NonCover** [HKUDS/UrbanGPT#6]
Hi！There is a RuntimeError with `python3 -m fastchat.serve.cli --model-path UrbanGPT/ --num-gpus 4`

`
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/root/miniconda3/envs/urbangpt/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/urbangpt/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/urbangpt/lib/python3.9/site-packages/fastchat/serve/cli.py", line 304, in <module>
    main(args)
  File "/root/miniconda3/envs/urbangpt/lib/python3.9/site-packages/fastchat/serve/cli.py", line 227, in main
    chat_loop(
  File "/root/miniconda3/envs/urbangpt/lib/python3.9/site-packages/fastchat/serve/inference.py", line 361, in chat_loop
    model, tokenizer = load_model(
  File "/root/miniconda3/envs/urbangpt/lib/python3.9/site-packages/fastchat/model/model_adapter.py", line 323, in load_model
    model, tokenizer = adapter.load_model(model_path, kwargs)
  File "/root/miniconda3/envs/urbangpt/lib/python3.9/site-packages/fastchat/model/model_adapter.py", line 85, in load_model
    model = AutoModelForCausalLM.from_pretrained(
  File "/root/miniconda3/envs/urbangpt/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 525, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/root/miniconda3/envs/urbangpt/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 1050, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/root/miniconda3/envs/urbangpt/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 748, in __getitem__
    raise KeyError(key)
KeyError: 'STLlama'
`

**Comment by LZH-YS1998** [comment]
Hello! It appears that running the model with the specified command might need some modifications. A simpler approach would be to follow the instructions in '4. Evaluating UrbanGPT' to test our model. You can find [STLlama.py](https://github.com/HKUDS/UrbanGPT/blob/main/urbangpt/model/STLlama.py) here.
